### ISSUE TITLE
UI is buggy and does not fit on higher resolutions

### ISSUE THREAD

**Issue by joeec** [enderprism/godot-dash-v2#1]
**Describe the bug**
The UI is buggy and does not fit properly on 1440p.

**To Reproduce**
1. Use resolution higher than 1080p
2. Open the game

**Expected behavior**
The UI to fit properly

**Screenshots**
![image](https://github.com/enderprism/godot-dash-v2/assets/165537498/7da80983-18e9-480f-8098-4fb2812c5505)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Godot version: 4.2.2

**Additional context**
You can use Virtual Super Resolution on an AMD GPU to test this on a low res monitor.

**Comment by enderprism** [comment]
[ace5f28](https://github.com/enderprism/godot-dash-v2/commit/ace5f28548498482297f5e723b4eeb503613ce56) should fix it. could you try it out?

**Comment by joeec** [comment]
This adds a black border:
![image](https://github.com/enderprism/godot-dash-v2/assets/165537498/5a9e65c1-db2f-4aaf-8799-2a90f20405d7)
Also present in gameplay:
![image](https://github.com/enderprism/godot-dash-v2/assets/165537498/c3528abe-0a4b-4228-8577-6a54e0d26815)

**Comment by enderprism** [comment]
does [389255a](https://github.com/enderprism/godot-dash-v2/commit/389255a74742fe2364e14e6d3178132466046bed) fix it?

**Comment by enderprism** [comment]
please respond :pray:

**Comment by joeec** [comment]
Sorry I forgot about this lmao, it does

![image](https://github.com/enderprism/godot-dash-v2/assets/165537498/45ba718b-b7ac-43c1-96c0-eeebcbfb9a51)
